### ISSUE TITLE
Update publish-latest.yml

### ISSUE THREAD

**Issue by silvalaura** [cengage/react-magma#688]
We should update [publish-latest](https://github.com/cengage/react-magma/blob/dev/.github/workflows/publish-latest.yml) so that we are less likely to release accidentally when something is pushed to the main branch.

We need to discuss as a team how we want to solve this.

Options: 
1. Don't automate this!
___
2. Keep automation, but update to:
- On push to master, ONLY run tests
- On merge to master, everything we currently do
- Remove `Sync main -> dev` step

Other things to still solve for:
- Could we select which version to release if there are changes for major/minor/patch within dev?
- Automate creating releases from tags in github

**Comment by silvalaura** [comment]
```
on:
  pull_request:
    branches:
      - deploy
    types: [closed]

jobs:
  <job id>:
    if: github.event.pull_request.merged == true
    steps: // the rest of the code
```
https://github.community/t/trigger-workflow-only-on-pull-request-merge/17359/9
